from node:10
ARG MYSQL_PASSWORD
WORKDIR /usr/app
RUN npm install express 
RUN npm install mysql 
RUN npm install body-parser 
RUN npm -y init

COPY ws/REST.js ws/
COPY ws/Server.js ws/
COPY ws/config ws/config
WORKDIR /usr/app/ws
RUN sed "s/<PASSWORD>/${MYSQL_PASSWORD}/g" > config/mysql.config.json < config/mysql.config.json-tmplt
RUN mv ../package.json .
RUN npm install

CMD [ "node", "Server.js" ]